version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    platform: linux/amd64
    env_file:
      - ./frontend/.env
    image: share-bill-frontend
    ports:
      - "3000:3000"
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    platform: linux/amd64
    env_file:
      - ./backend/.env
    image: share-bill-backend
    ports:
      - "5050:5050"
    restart: unless-stopped
